
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and unit test pipeline ##

on: #[push] # to run it on every push on any branch
  push:
    branches-ignore:
      - main
  #workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
#defaults:
#  run:
#    working-directory: 'BE'
jobs:
  BE:
    name: Build and test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'BE'
    steps:
    - name: Checkout code from repo
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    #- name: Cache Maven packages
    #  uses: actions/cache@v3
    #  with:
    #    path: ~/.m2
    #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #    restore-keys: ${{ runner.os }}-m2
    - name: Build and sonar analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=WilhelmStu_test_repo
    - name: pitest code
      run: mvn -DwithHistory test-compile org.pitest:pitest-maven:mutationCoverage
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml

    # this is not working in multi-module repos.. :(
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: Java build test report
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit


  FE:
    name: Build and test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'FE'
    steps:
    - name: Checkout code from repo
      uses: actions/checkout@v3
    - name: show tree
      run: tree
    - name: Node.js setup
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run test:ci

