
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Selenium tests

on: #[push] # to run it on every push on any branch
  #workflow_run:
  #  workflows: ["build_test"]
  #  types:
  #    - complete
  push: # todo remove -dev
    branches:
      - dev
  #pull_request:
  #  types: [opened, reopened]

jobs:
  #unitTest:
  # #if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #  uses: ./.github/workflows/build_test.yml
  build:
    name: Build and analyze
    #needs: [unitTest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: show tree
      run: tree
    - name: run spring server file
      working-directory: ./BE
      run: |
        mvn spring-boot:run &
        sleep 5
    - name: Test selenium
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      uses: actions/checkout@v3
      with:
        path: 'selenium'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: test
      run: mvn clean test
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: Test report >
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit

